# Generated by Django 5.2.10 on 2026-02-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_learnerprofile_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(editable=False, help_text='Unique session identifier', unique=True)),
                ('skill_topic', models.CharField(help_text="e.g., 'Python Backend Development'", max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('cv_text', models.TextField(blank=True, help_text='Parsed CV/resume text')),
                ('system_prompt', models.TextField(help_text='Gemini system instruction for this session')),
                ('tavus_persona_id', models.CharField(blank=True, help_text='Tavus persona ID', max_length=100)),
                ('tavus_conversation_id', models.CharField(blank=True, help_text='Tavus conversation ID', max_length=100)),
                ('conversation_url', models.URLField(blank=True, help_text='Daily.co WebRTC URL for embedding')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('ended', 'Ended'), ('error', 'Error')], default='ready', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total interview duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interview Session',
                'verbose_name_plural': 'AI Interview Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_summary', models.TextField(help_text='1-2 sentence overall assessment')),
                ('strengths', models.JSONField(default=list, help_text='List of key strengths')),
                ('improvements', models.JSONField(default=list, help_text='List of areas to improve')),
                ('topic_knowledge_score', models.IntegerField(default=5, help_text='Knowledge of interview topic')),
                ('communication_score', models.IntegerField(default=5, help_text='Clarity of explanation')),
                ('problem_solving_score', models.IntegerField(default=5, help_text='Problem-solving approach')),
                ('overall_score', models.IntegerField(default=5, help_text='Overall performance (average)')),
                ('recommendation', models.TextField(blank=True, help_text='Should candidate proceed? Why?')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report', to='api.aiinterviewsession')),
            ],
            options={
                'verbose_name': 'AI Performance Report',
                'verbose_name_plural': 'AI Performance Reports',
            },
        ),
        migrations.CreateModel(
            name='InterviewTranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('user', 'User'), ('ai', 'AI Interviewer')], max_length=10)),
                ('text', models.TextField(blank=True, help_text='Transcribed text (if available)')),
                ('audio_data', models.TextField(blank=True, help_text='Base64 encoded audio chunk (optional)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField(default=0, help_text='Order in conversation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_entries', to='api.aiinterviewsession')),
            ],
            options={
                'verbose_name': 'Interview Transcript Entry',
                'verbose_name_plural': 'Interview Transcript Entries',
                'ordering': ['session', 'sequence_number'],
            },
        ),
    ]
