# Generated by Django 5.2.10 on 2026-02-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_aiinterviewsession_aiperformancereport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who started the interview (optional for testing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
