# Generated by Django 5.2.10 on 2026-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_make_user_optional_in_ai_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='conversation_url',
            field=models.URLField(blank=True, help_text='Daily.co WebRTC URL for embedding', null=True),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='tavus_conversation_id',
            field=models.CharField(blank=True, help_text='Tavus conversation ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='tavus_persona_id',
            field=models.CharField(blank=True, help_text='Tavus persona ID', max_length=100, null=True),
        ),
    ]
