# Generated by Django 6.0.2 on 2026-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_aiinterviewsession_conversation_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='badge_asset_id',
            field=models.BigIntegerField(blank=True, help_text='Algorand ASA ID for skill badge NFT', null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='algo_wallet',
            field=models.CharField(blank=True, help_text='Algorand wallet address for NFT delivery', max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='nft_asset_id',
            field=models.BigIntegerField(blank=True, help_text='Algorand ASA ID for certificate NFT', null=True),
        ),
    ]
