# Generated by Django 6.0.2 on 2026-02-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_assessmentresult_badge_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='pending_skill_tokens',
            field=models.IntegerField(default=0, help_text='$SKILL tokens earned but not yet transferred on-chain (e.g. wallet not opted-in)'),
        ),
    ]
