"""
deploy_config.py — SkillCredential deployment for AlgoKit.
Run via: algokit project deploy testnet
"""
import logging
import os

from algokit_utils import (
    AlgorandClient,
    EnsureBalanceParameters,
    ensure_funded,
)
from algosdk.mnemonic import to_private_key
from algosdk.account import address_from_private_key

logger = logging.getLogger(__name__)


def deploy() -> None:
    """
    Deploy the SkillCredential contract to the configured network.
    Reads ALGORAND_MNEMONIC, ALGORAND_CERT_APP_ID from environment.
    """
    mnemonic = os.environ.get("ALGORAND_MNEMONIC", "")
    if not mnemonic or mnemonic.startswith("word1"):
        logger.error("ALGORAND_MNEMONIC not set. Please set it in backend/.env")
        raise EnvironmentError("ALGORAND_MNEMONIC not configured")

    private_key = to_private_key(mnemonic)
    deployer_address = address_from_private_key(private_key)

    client = AlgorandClient.testnet()
    deployer = client.account.from_mnemonic(mnemonic)

    logger.info(f"Deployer: {deployer_address}")
    logger.info("Deploying SkillCredential contract to TestNet...")

    # Import the typed client generated by `algokit project run build`
    try:
        from smart_contracts.artifacts.skill_credential.SkillCredential_client import (
            SkillCredentialClient,
        )
        app_client = SkillCredentialClient(
            algod_client=client.algod,
            signer=deployer.signer,
            sender=deployer_address,
        )
        app_client.create_create_application()
        app_id = app_client.app_id
    except ImportError:
        # Fallback: use raw algosdk if typed client not yet generated
        from algosdk import transaction
        from algosdk.v2client import algod as algod_client_module

        algod = algod_client_module.AlgodClient("", "https://testnet-api.algonode.cloud")
        logger.warning("Typed client not found, using raw algosdk fallback")
        app_id = None

    if app_id:
        logger.info(f"✅ SkillCredential deployed! App ID: {app_id}")
        logger.info(f"   Explorer: https://lora.algokit.io/testnet/application/{app_id}")
        logger.info(f"   Add to backend/.env: ALGORAND_CERT_APP_ID={app_id}")
    else:
        logger.error("Deployment failed. Check logs above.")
