"""
deploy_config.py — SkillBadge deployment for AlgoKit.
Run via: algokit project deploy testnet
Requires ALGORAND_SKILL_TOKEN_ID to already be set (run scripts/create_skill_token.py first).
"""
import logging
import os

from algokit_utils import AlgorandClient
from algosdk.mnemonic import to_private_key
from algosdk.account import address_from_private_key

logger = logging.getLogger(__name__)


def deploy() -> None:
    """
    Deploy the SkillBadge contract to the configured network.
    Reads ALGORAND_MNEMONIC and ALGORAND_SKILL_TOKEN_ID from environment.
    """
    mnemonic = os.environ.get("ALGORAND_MNEMONIC", "")
    if not mnemonic or mnemonic.startswith("word1"):
        logger.error("ALGORAND_MNEMONIC not set. Please set it in backend/.env")
        raise EnvironmentError("ALGORAND_MNEMONIC not configured")

    skill_token_id = int(os.environ.get("ALGORAND_SKILL_TOKEN_ID", "0") or "0")
    if skill_token_id == 0:
        logger.error("ALGORAND_SKILL_TOKEN_ID not set. Run scripts/create_skill_token.py first.")
        raise EnvironmentError("ALGORAND_SKILL_TOKEN_ID not configured")

    private_key = to_private_key(mnemonic)
    deployer_address = address_from_private_key(private_key)

    client = AlgorandClient.testnet()
    deployer = client.account.from_mnemonic(mnemonic)

    logger.info(f"Deployer: {deployer_address}")
    logger.info(f"$SKILL Token ID: {skill_token_id}")
    logger.info("Deploying SkillBadge contract to TestNet...")

    # Import the typed client generated by `algokit project run build`
    try:
        from smart_contracts.artifacts.skill_badge.SkillBadge_client import (
            SkillBadgeClient,
        )
        app_client = SkillBadgeClient(
            algod_client=client.algod,
            signer=deployer.signer,
            sender=deployer_address,
        )
        app_client.create_create_application(skill_token_asset_id=skill_token_id)
        app_id = app_client.app_id
    except ImportError:
        logger.warning("Typed client not found, using raw algosdk fallback")
        app_id = None

    if app_id:
        logger.info(f"✅ SkillBadge deployed! App ID: {app_id}")
        logger.info(f"   Explorer: https://lora.algokit.io/testnet/application/{app_id}")
        logger.info(f"   Add to backend/.env: ALGORAND_BADGE_APP_ID={app_id}")
    else:
        logger.error("Deployment failed. Check logs above.")
